# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lovely-grad',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/lovely-grad',
                'lib_path': 'lovely_grad'},
  'syms': {'lovely_grad.core': {'lovely_grad.core.foo': ('core.html#foo', 'lovely_grad/core.py')}}}
