name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install latest tinygrad
        shell: bash
        run: |
          pip install -Uq git+https://github.com/xl0/tinygrad

      - uses: fastai/workflows/quarto-ghp@master
