name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    name: 'nbdev-ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "pip"
          cache-dependency-path: settings.ini
      - name: Test with nbdev
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -U git+https://github.com/tinygrad/tinygrad

          echo "Doing editable install..."
          test -f setup.py && pip install -e ".[dev]"
          echo "Check we are starting with clean git checkout"
          if [[ `git status --porcelain -uno` ]]; then
            git diff
            echo "git status is not clean"
            false
          fi
          echo "Trying to strip out notebooks"
          nbdev_clean
          echo "Check that strip out was unnecessary"
          git status -s # display the status to see which nbs need cleaning up
          if [[ `git status --porcelain -uno` ]]; then
            git status -uno
            echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
            echo -e "This error can also happen if you are using an older version of nbdev relative to what is in CI.  Please try to upgrade nbdev with the command `pip install -U nbdev`"
            false
          fi
          nbdev_export
          if [[ `git status --porcelain -uno` ]]; then
            echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
            git status -uno
            git diff
            exit 1;
          fi
          nbdev_test --n_workers 0

